version: 2
jobs:
  build:
    working_directory: ~/aerogear
    docker:
      # Node 8 LTS
      - image: circleci/node:carbon
    steps:
      - checkout
      - run:
          name: install-dependencies
          command: npm install
      - run:
          name: run lint
          command: npm run lint
      - run:
          name: run coverage
          command: npm run coverage
      - run:
          name: send coverage report to coveralls
          command: cat ./coverage/lcov.info | coveralls

workflows:
  version: 2
  build_and_release:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/